version: "3"
services: 
  app: 
    image: node:16-alpine
    restart: always
    user: node
    working_dir: /home/node/app 
    ports: 
      - 3000:3000
    volumes:
      - ./:/home/node/app
    command: "node index.mjs"
